language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-testangular' ]; then cd .. && eval "mv $currentfolder generator-testangular" && cd generator-testangular; fi

